# gregson Configuration
# config for laptop w/ Nvidia GTX 960

{ config, lib, pkgs, ... }:{

  # Imports
  imports =[ 
    ./hardware-configuration.nix # hardware config (generated by NixOS)
    ./../../modules/defaults.nix # default settings & programs
    ./../../modules/graphical.nix # graphical environment
  ];

  # DO NOT CHANGE
  system.stateVersion = "24.05";

  # Networking and Host name
  networking.hostName = "gregson";
  networking.networkmanager.enable = true;

  # Bootloader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Nvidia settings
  # hardware.opengl.enable = true;
  # hardware.nvidia = {
  #   modesetting.enable = true;
  #   powerManagement.enable = false;
  #   powerManagement.finegrained = false;
  #   open = false;
  #   nvidiaSettings = true;
  #   package = config.boot.kernelPackages.nvidiaPackages.stable;
  # };
  # services.xserver.videoDrivers = [ "nvidia" ]; # Graphics drivers

  # Sound settings
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    jack.enable = true;
  };

  # VirtualBox
  virtualisation.virtualbox.host.enable = true;
  virtualisation.virtualbox.host.enableExtensionPack = true;

  # Users
  users.users.minimumaction = {
    isNormalUser = true;
    description = "Kevin Liguori";
    extraGroups = [ "networkmanager" "wheel" "vboxusers" ];
  };

  # Host specific system packages
  environment.systemPackages = with pkgs; [
    anki-bin
  ];

}
