# ltNixOS configuration

{ config, lib, pkgs, ... }:{

  # Imports
  imports =[ 
    ./hardware-configuration.nix # hardware config (generated by NixOS)
    ./../../nixosModules/defaults.nix # default settings/programs
    ./../../nixosModules/graphical.nix # graphical environment
  ];

  # DO NOT CHANGE
  system.stateVersion = "24.05";

  # Host name
  networking.hostName = "ltNixOS";

  # Bootloader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Drivers for external wifi adapter
  boot.extraModulePackages = with config.boot.kernelPackages; [ rtl8812au ];
  boot.initrd.kernelModules = [ "8812au" ];

  # Touchpad
  services.libinput.enable = true;

  # Sound
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    jack.enable = true;
  };

  # Users
  users.users.minimumaction = {
    isNormalUser = true;
    description = "Kevin Liguori";
    extraGroups = [ "networkmanager" "wheel" ];
  };

  # Host specific system packages
  environment.systemPackages = with pkgs; [];

}