# sherlock Configuration
# config for home desktop w/ AMD CPU and Nvidia RTX 2080 Ti

{ config, lib, pkgs, ... }:{

  # Imports
  imports =[ 
    ./hardware-configuration.nix # hardware config (generated by NixOS)
    ./../../modules/desktop-environments/budgie.nix # desktop environment
    ./../../modules/defaults.nix # default settings & programs
    ./../../modules/graphical.nix # graphical programs
  ];

  # DO NOT CHANGE
  system.stateVersion = "24.05";

  # Networking and Host name
  networking.hostName = "sherlock";
  networking.networkmanager.enable = true;

  # Bootloader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Keyboard settings
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # Graphics settings
  services.xserver.videoDrivers = [ "nvidia" ]; # Graphics drivers
  hardware = {
    opengl.enable = true;
    nvidia = {
      modesetting.enable = true;
      powerManagement.enable = false;
      powerManagement.finegrained = false;
      open = false;
      nvidiaSettings = true;
      package = config.boot.kernelPackages.nvidiaPackages.stable;
    };
  };

  # Sound settings
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    jack.enable = true;
  };

  # VirtualBox
  virtualisation.virtualbox.host.enable = true;
  virtualisation.virtualbox.host.enableExtensionPack = true;

  # Users
  users.users.minimumaction = {
    isNormalUser = true;
    description = "Kevin Liguori";
    extraGroups = [ "networkmanager" "wheel" "vboxusers" ];
  };

  # Host specific system packages
  environment.systemPackages = with pkgs; [];

}
