# lestrade configuration.nix
# config for old 2011 macbook air

{ config, lib, pkgs, ... }:{

  # Imports
  imports = [
    ./hardware-configuration.nix # hardware config (generated by NixOS)
    ./../../modules/defaults.nix # default settings & programs
    ./../../modules/xmonad.nix # graphical environment
  ];

  # DO NOT CHANGE
  system.stateVersion = "24.05";
  
  # Networking and hostname
  networking.hostName = "lestrade"; 
  networking.networkmanager.enable = true;

  # Boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Drivers for external wifi adapter
  boot.extraModulePackages = with config.boot.kernelPackages; [ rtl8812au ];
  boot.initrd.kernelModules = [ "8812au" ];

  # Keyboard layout and touchpad support
  services = {
    xserver.xkb = {
      layout = "us";
      variant = "mac";
    };
    libinput.enable = true;
  };

  # Sound settings
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    jack.enable = true;
  };

  # Users
  users.users.minimumaction = {
    isNormalUser = true;
    description = "Kevin Liguori";
    extraGroups = [ "networkmanager" "wheel" ];
  };

  # Host specific system packages
  environment.systemPackages = with pkgs; [];

}

